"""added diagnostic column

Revision ID: 3d43528ad11a
Revises: 6e6407432048
Create Date: 2024-11-01 12:53:40.251426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d43528ad11a'
down_revision = '6e6407432048'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobcards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diagnostic', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobcards', schema=None) as batch_op:
        batch_op.drop_column('diagnostic')

    # ### end Alembic commands ###
