"""empty message

Revision ID: 4793f5b9eefe
Revises: 3d43528ad11a
Create Date: 2024-11-03 17:04:58.772872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4793f5b9eefe'
down_revision = '3d43528ad11a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobcards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_technician_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['assigned_technician_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobcards', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('assigned_technician_id')

    # ### end Alembic commands ###
