"""empty message

Revision ID: 7cb3bfb5c30b
Revises: 8ee45bf8e6a2
Create Date: 2024-10-25 12:26:25.356928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cb3bfb5c30b'
down_revision = '8ee45bf8e6a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.alter_column('warranty_status',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.alter_column('warranty_status',
               existing_type=sa.String(length=100),
               type_=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
