"""empty message

Revision ID: 8ee45bf8e6a2
Revises: 8d8148364b54
Create Date: 2024-10-19 15:00:18.302191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ee45bf8e6a2'
down_revision = '8d8148364b54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=True))
        batch_op.drop_column('_password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('password')

    # ### end Alembic commands ###
