"""Update client field lengths

Revision ID: 985881b2a5c8
Revises: ed602d685cd2
Create Date: 2024-10-18 09:45:41.759302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '985881b2a5c8'
down_revision = 'ed602d685cd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
