"""empty message

Revision ID: ac64c0b6e2e2
Revises: 7cb3bfb5c30b
Create Date: 2024-10-25 12:40:53.069405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac64c0b6e2e2'
down_revision = '7cb3bfb5c30b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobcards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_description', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobcards')
    # ### end Alembic commands ###
