"""Add timestamp to jobcards

Revision ID: fe91e61d4cca
Revises: ac64c0b6e2e2
Create Date: 2024-10-25 14:42:59.609692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe91e61d4cca'
down_revision = 'ac64c0b6e2e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobcards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobcards', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
